/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package tabuleironetbeans;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author viwjcq
 */
public class Tabuleiro_2 extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    final Color marrom = new Color(102,51,0);
    final Color marromFileira = new Color(156,73,0);
    final Color marromEspaco = new Color(51,25,0);
    final Dimension tamFileira = new Dimension(624,100);
    final Dimension tamEspaco = new Dimension(90,110);
    
    private void criarFileira(JPanel fileira){
        fileira.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        fileira.setBackground(marromFileira);
        fileira.setPreferredSize(tamFileira);
    }
    
    private void criarEspaco(JPanel espaco){
        espaco.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        espaco.setBackground(marromEspaco);
        espaco.setPreferredSize(tamEspaco);
    }
    
    public Tabuleiro_2() {
        initComponents();
        getContentPane().setBackground(marrom);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        placar = new javax.swing.JPanel();
        fileiraCerco = new javax.swing.JPanel();
        fileiraLongaDistancia = new javax.swing.JPanel();
        fileiraInfantaria = new javax.swing.JPanel();
        divisor = new javax.swing.JPanel();
        fileiraInfantariaAd = new javax.swing.JPanel();
        fileiraLongaDistanciaAd = new javax.swing.JPanel();
        fileiraCercoAd = new javax.swing.JPanel();
        deck = new javax.swing.JPanel();
        cemiterio = new javax.swing.JPanel();
        deckAd = new javax.swing.JPanel();
        cemiterioAd = new javax.swing.JPanel();
        espacoCartas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel placar = new JPanel();
        placar.setBackground(Color.BLUE);

        javax.swing.GroupLayout placarLayout = new javax.swing.GroupLayout(placar);
        placar.setLayout(placarLayout);
        placarLayout.setHorizontalGroup(
            placarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        placarLayout.setVerticalGroup(
            placarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        fileiraCerco.setPreferredSize(new java.awt.Dimension(624, 100));
        fileiraCerco.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        fileiraCerco.setBackground(marromFileira);
        fileiraCerco.setPreferredSize(tamFileira);

        javax.swing.GroupLayout fileiraCercoLayout = new javax.swing.GroupLayout(fileiraCerco);
        fileiraCerco.setLayout(fileiraCercoLayout);
        fileiraCercoLayout.setHorizontalGroup(
            fileiraCercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        fileiraCercoLayout.setVerticalGroup(
            fileiraCercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        fileiraLongaDistancia.setPreferredSize(new java.awt.Dimension(624, 100));
        fileiraLongaDistancia.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        fileiraLongaDistancia.setBackground(marromFileira);
        fileiraLongaDistancia.setPreferredSize(tamFileira);

        javax.swing.GroupLayout fileiraLongaDistanciaLayout = new javax.swing.GroupLayout(fileiraLongaDistancia);
        fileiraLongaDistancia.setLayout(fileiraLongaDistanciaLayout);
        fileiraLongaDistanciaLayout.setHorizontalGroup(
            fileiraLongaDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        fileiraLongaDistanciaLayout.setVerticalGroup(
            fileiraLongaDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        fileiraInfantaria.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        fileiraInfantaria.setBackground(marromFileira);
        fileiraInfantaria.setPreferredSize(tamFileira);

        javax.swing.GroupLayout fileiraInfantariaLayout = new javax.swing.GroupLayout(fileiraInfantaria);
        fileiraInfantaria.setLayout(fileiraInfantariaLayout);
        fileiraInfantariaLayout.setHorizontalGroup(
            fileiraInfantariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fileiraInfantariaLayout.setVerticalGroup(
            fileiraInfantariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        divisor.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        javax.swing.GroupLayout divisorLayout = new javax.swing.GroupLayout(divisor);
        divisor.setLayout(divisorLayout);
        divisorLayout.setHorizontalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        divisorLayout.setVerticalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        criarFileira(fileiraInfantariaAd);

        javax.swing.GroupLayout fileiraInfantariaAdLayout = new javax.swing.GroupLayout(fileiraInfantariaAd);
        fileiraInfantariaAd.setLayout(fileiraInfantariaAdLayout);
        fileiraInfantariaAdLayout.setHorizontalGroup(
            fileiraInfantariaAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fileiraInfantariaAdLayout.setVerticalGroup(
            fileiraInfantariaAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        criarFileira(fileiraLongaDistanciaAd);

        javax.swing.GroupLayout fileiraLongaDistanciaAdLayout = new javax.swing.GroupLayout(fileiraLongaDistanciaAd);
        fileiraLongaDistanciaAd.setLayout(fileiraLongaDistanciaAdLayout);
        fileiraLongaDistanciaAdLayout.setHorizontalGroup(
            fileiraLongaDistanciaAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fileiraLongaDistanciaAdLayout.setVerticalGroup(
            fileiraLongaDistanciaAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        criarFileira(fileiraCercoAd);

        javax.swing.GroupLayout fileiraCercoAdLayout = new javax.swing.GroupLayout(fileiraCercoAd);
        fileiraCercoAd.setLayout(fileiraCercoAdLayout);
        fileiraCercoAdLayout.setHorizontalGroup(
            fileiraCercoAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fileiraCercoAdLayout.setVerticalGroup(
            fileiraCercoAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        criarEspaco(deck);

        javax.swing.GroupLayout deckLayout = new javax.swing.GroupLayout(deck);
        deck.setLayout(deckLayout);
        deckLayout.setHorizontalGroup(
            deckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        deckLayout.setVerticalGroup(
            deckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        criarEspaco(cemiterio);

        javax.swing.GroupLayout cemiterioLayout = new javax.swing.GroupLayout(cemiterio);
        cemiterio.setLayout(cemiterioLayout);
        cemiterioLayout.setHorizontalGroup(
            cemiterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cemiterioLayout.setVerticalGroup(
            cemiterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        criarEspaco(deckAd);

        javax.swing.GroupLayout deckAdLayout = new javax.swing.GroupLayout(deckAd);
        deckAd.setLayout(deckAdLayout);
        deckAdLayout.setHorizontalGroup(
            deckAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        deckAdLayout.setVerticalGroup(
            deckAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        criarEspaco(cemiterioAd);

        javax.swing.GroupLayout cemiterioAdLayout = new javax.swing.GroupLayout(cemiterioAd);
        cemiterioAd.setLayout(cemiterioAdLayout);
        cemiterioAdLayout.setHorizontalGroup(
            cemiterioAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cemiterioAdLayout.setVerticalGroup(
            cemiterioAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        espacoCartas.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        espacoCartas.setBackground(marromEspaco);

        javax.swing.GroupLayout espacoCartasLayout = new javax.swing.GroupLayout(espacoCartas);
        espacoCartas.setLayout(espacoCartasLayout);
        espacoCartasLayout.setHorizontalGroup(
            espacoCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        espacoCartasLayout.setVerticalGroup(
            espacoCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(placar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(espacoCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileiraLongaDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileiraCerco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileiraCercoAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileiraLongaDistanciaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileiraInfantaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileiraInfantariaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deckAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cemiterioAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileiraCercoAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileiraLongaDistanciaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(placar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileiraInfantariaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fileiraInfantaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileiraLongaDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileiraCerco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(espacoCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deckAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cemiterioAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cemiterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JPanel cemiterio;
    private javax.swing.JPanel cemiterioAd;
    private javax.swing.JPanel deck;
    private javax.swing.JPanel deckAd;
    private javax.swing.JPanel divisor;
    private javax.swing.JPanel espacoCartas;
    private javax.swing.JPanel fileiraCerco;
    private javax.swing.JPanel fileiraCercoAd;
    private javax.swing.JPanel fileiraInfantaria;
    private javax.swing.JPanel fileiraInfantariaAd;
    private javax.swing.JPanel fileiraLongaDistancia;
    private javax.swing.JPanel fileiraLongaDistanciaAd;
    private javax.swing.JPanel placar;
    // End of variables declaration                   
}
